databases:
  - name: servidorCristian
    plan: free
    databaseName: dbcine
    user: cristian

services:
  - type: web
    plan: free
    name: cineUTC
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn cineUTC.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: servidorCristian
          property: externalConnectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: cineutc-f7rs.onrender.com




# set DATABASE_URL=postgresql://cristian:b0S6xY2F8dHzXPNRzPDNX7FBD9EG4PwI@dpg-cqlpki3v2p9s73bfvr70-a.oregon-postgres.render.com/dbcine_zaun